### ISSUE TITLE
[Bug] 频繁的 TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/curriculum-board-frontend-vue2#22]
未知原因的 Bug，通常在首次载入中和打开首页后出现，导致搜索功能不能正常使用。清空所有本地数据（Cookie、Indexed DB 等）后恢复正常。

报错原因未知，位置见下。

![image](https://user-images.githubusercontent.com/8389787/216392396-59a37fa9-3680-4ae7-947b-138813ef40a2.png)

**Comment by KYLN24** [comment]
这从编译后的代码找源码中的位置似乎有点困难

**Comment by ivanfei-1** [comment]
`src/utils/tokenize.ts`中的 `initializeTokenize`出的问题, 需检查分词表是哪里提供的

**Comment by ivanfei-1** [comment]
Fixed in 1acd830661eba5f995674c998518d9842c3e7e97

But I'm not sure if this is fixed.

**Comment by w568w** [comment]
这看起来应该没有解决问题。从报错来看，显然为 `undefined` 的是 `(await tokenText.toArray())[0]` 而不是 `text`。
