### ISSUE TITLE
[Feature Request] 建立个人主页

### ISSUE THREAD

**Issue by QLTyrone** [OpenTreeHole/curriculum-board-frontend-vue2#24]
**此Issue搬运自飞书原《功能需求和bug修复建议》文档**

**备注**
可以查看已发布课评，展示徽章、获赞数等

**提出部门**
公关联络部

**Comment by w568w** [comment]
同样需要后端支援。请复制一份至 https://github.com/OpenTreeHole/curriculum_board_backend_next/issues，然后在这里引用它。

**Comment by w568w** [comment]
Close due to stale.
